[package]
name = "bevy_prototype_input_map"
version = "0.1.0"
edition = "2018"
authors = ["Pradeep Kumar Rajamanickam <raj.pradeep.kumar@gmail.com>"]
description = "Adds support for input mapping"
example = "https://github.com/PradeepKumarRajamanickam/bevy_input_map"
license = "MIT"

[dependencies]
# bevy
bevy = "0.1.3"
bevy_app = "0.1"
bevy_ecs = "0.1"
bevy_input = "0.1"

[[example]]
name = "input_map"
path = "example/input_map.rs"